update-checker: true

recipes:
  example_pickaxe:
    # The shape is a grid of characters, where each character represents a material.
    shape:
      - "AAA"
      - " B "
      - " B "

    # Explanation: A = EMERALD, B = STICK
    ingredients:
      A:
        material: "EMERALD"
      B:
        material: "STICK"

    # The result is the item that is crafted.
    result:
      material: "DIAMOND_PICKAXE"
      name: "Emerald Pickaxe"

  example_sword:
    shape:
      - "A"
      - "A"
      - "B"
    ingredients:
      A:
        material: "EMERALD"
      B:
        material: "STICK"
    result:
      material: "DIAMOND_SWORD"
      name: "Emerald Sword"