update-checker: true

recipes:
  example_pickaxe:
    type: "CRAFTING"
    shape:
      - "AAA"
      - " B "
      - " B "

    ingredients:
      A:
        ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: EMERALD
      B:
        ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: STICK

    result:
      ==: org.bukkit.inventory.ItemStack
      v: 3465
      type: DIAMOND_PICKAXE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"text":"Emerald Pickaxe"}'
        enchants:
          DIG_SPEED: 5
        repair-cost: 1

    example_reforge_helmet:
      type: FURNACE
      result:
        ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: IRON_INGOT
        amount: 2
      ingredient:
        ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: IRON_HELMET
      experience: 0
      cookingTime: 100

    example_reforge_chestplate:
      type: FURNACE
      result:
        ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: IRON_INGOT
        amount: 4
      ingredient:
        ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: IRON_CHESTPLATE
      experience: 0
      cookingTime: 100

    example_reforge_leggings:
      type: FURNACE
      result:
        ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: IRON_INGOT
        amount: 3
      ingredient:
        ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: IRON_LEGGINGS
      experience: 0
      cookingTime: 100

    example_reforge_boots:
      type: FURNACE
      result:
        ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: IRON_INGOT
        amount: 2
      ingredient:
        ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: IRON_BOOTS
      experience: 0
      cookingTime: 100