update-checker: true

recipes:
  example_pickaxe:
    # The shape is a grid of characters, where each character represents a material.
    shape:
      - "AAA"
      - " B "
      - " B "

    # Explanation: A = EMERALD, B = STICK
    ingredients:
      A:
        ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: EMERALD
      B:
        ==: org.bukkit.inventory.ItemStack
        v: 3465
        type: STICK

    # The result is the item that is crafted.
    result:
      ==: org.bukkit.inventory.ItemStack
      v: 3465
      type: DIAMOND_PICKAXE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"text":"Emerald Pickaxe"}'
        enchants:
          DIG_SPEED: 5
        repair-cost: 1